#! /bin/bash

# Here, we import all submodules automatically as their folder names.

if [ $# -le 0 ]; then
	echo 'This program a single directory as its argument'
	exit
fi
cd "$1"
shopt -s globstar
for i in **/; do
	all_dirs=
	for j in */; do
		all_dirs="${all_dirs}import ${j%/}\n"
	done
	for j in $i*.py; do
		echo "$j" | grep -P '\*|__' >& /dev/null
		if [ $? -eq 0 ]; then
			continue
		fi
		sed -i "1i $all_dirs" "$j"
	done
done
