#! /bin/bash

# Here, we import all submodules automatically as their
# folder names.

if [ $# -le 0 ]; then
	echo 'This program a single directory as its argument'
	exit
fi

function getAllImports {
	all_dirs=
	for j in "$1"*/; do
		j=${j%/}
		j=${j##*/}
		all_dirs="${all_dirs}import $j\n"
	done
	echo $all_dirs
}

cd "$1"
shopt -s globstar
for i in **/; do
	all_dirs=$(getAllImports "$i")
	for j in $i*.py; do
		echo "$j" | grep -P '\*|__' >& /dev/null
		if [ $? -eq 0 ]; then
			continue
		fi
		sed -i "1i $all_dirs" "$j"
	done
done
