#! /bin/bash

# Here, we import all submodules automatically as their
# folder names.

if [ $# -le 0 ]; then
	echo 'This program a single directory as its argument'
	exit
fi

function getAllImports {
	all_dirs=''
	for j in "$1"*/; do
		j=${j%/}
		j=${j##*/}
		# Add a new import because we want linting to succeed.
		echo "$j" | grep '\*' > /dev/null
		if [ $? -eq 1 ]; then
			all_dirs="${all_dirs}import $j\n"
		fi
	done
	echo $all_dirs
}

cd "$1"
shopt -s globstar
for i in **/; do
	all_dirs=$(getAllImports "$i")
	for j in $i*.py; do
		echo "$j" | grep -P '\*|__' >& /dev/null
		if [ $? -eq 0 ]; then
			continue
		fi
		if [ "$all_dirs" != '' ]; then
			sed -i "1i $all_dirs" "$j"
		fi
	done
done


other=Main.py
if [ -f "$other" ]; then
	all_dirs=$(getAllImports)
	if [ "$all_dirs" != '' ]; then
		sed -i "2i $all_dirs" "$other"
	fi
fi
