#! /bin/bash

# Automatically copy a single system, process it using
# autotools.
# Then run it through the interpreter.
# Currently runs from the directory it is in.
# Copies to parent directory.

scrdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
curdir="$(pwd)"
pardir="${curdir%/*}"
cd "$pardir"

"$scrdir/transform" "$curdir"
"$pardir/transformed/Main.py"
