#! /bin/bash

# Automatically copy a single system, process it using
# autotools.
# Then run it through the interpreter.
# Currently runs from the directory it is in.
# Copies to parent directory.

function getScriptDir {
	script_dir="${0%/*}"
	echo $script_dir
}

curdir="$(pwd)"
pardir="${curdir%/*}"
cd "$pardir"
scrdir="$(getScriptDir)"

"$scrdir/transform" "$curdir"
"$pardir/transformed/Main.py"
