#! /bin/bash

# The purpose of this script is to call all usefull transforms.
# 1. It copies the directory
# 2. It runs the __init__.py generator
# 3. It runs the classifier
# 4. It runs the autoimporter

if [ $# -lt 1 ]; then
	echo 'This script requires a directory to copy. It will be placed in "transformed" folder in the current working directory'
	echo 'A second argument can be used to specify the name of the directory (via a move)'
	exit 1
fi

if [ -d 'transformed' ] && [ ! -f 'transformed/ignore' ] || [ -d "$2" ] && [ ! -f "$2/ignore" ]; then
	echo 'WARNING: transformed directory already exists without an ignore file in it. Aborting.'
	exit 2
fi

function getScriptDir {
	script_dir="${0%/*}"
	echo $script_dir
}

if [ -d transformed ]; then rm -r transformed; fi
script_dir="$(getScriptDir)"
cp -r "$1" transformed/
touch transformed/ignore
$script_dir/importify "$(pwd)/transformed"
$script_dir/classify "$(pwd)/transformed"
$script_dir/autoimport "$(pwd)/transformed"

if [ $# -eq 2 ]; then
	mv transformed/ "$2"
fi
